FROM centos:7
MAINTAINER Edison E. Abreu <edison@amixsi.com.br>
RUN yum install -y gcc git python-setuptools python-devel libtiff-devel libjpeg-devel libzip-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel
RUN easy_install virtualenv
